version: '3'
services:
  mongodb:
    build:
      context: ./4tellr-app
      dockerfile: docker/Dockerfile
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: 4tellr
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
